server: 
  port: 8080
  servlet: 
    context-path: /um-webapp-client
    
logging: 
  level:
    root: INFO
    reactor.netty.channel.ChannelOperationsHandler: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    
baeldung:
  resource-uri: http://localhost:8081/um-webapp-resource-server/api/foos/1
    
spring: 
  security: 
    oauth2: 
      client: 
        registration: 
          bael: 
            authorization-grant-type: client_credentials
            client-id: lssClient
            client-secret: lssSecret
        provider: 
          bael: 
            token-uri: http://localhost:8083/um-webapp-auth-server/oauth/token
    
